### ISSUE TITLE
BufferedTempfileStorageHandler should close files between reads/writes

### ISSUE THREAD

**Issue by rowleya** [SpiNNakerManchester/SpiNNStorageHandlers#13]
The BufferedTempfileStorageHandler keeps a tempfile open forever.  Instead, it should create a NamedTemporaryFile and set it to not delete on close.  It should then open and close the file as it is read and/or written (writes would be append by default).  An "exit handler" should then also be added so that the file is deleted when the program exits.

**Comment by dkfellows** [comment]
There should be a single exit handler to delete all the (known) temporary files, rather than registering masses of them. Like that, deregistering a particular file because it has been explicitly closed by user code becomes a simple operation.

**Comment by Christian-B** [comment]
We are moving to sqllite base which is making BufferedTempfileDataStorage obsolete.
