### ISSUE TITLE
AbstractDataWriter.tell 

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/SpiNNStorageHandlers#26]
Is this method used anywhere usefull??????

If not delete!

if yes need to understand what for the database version.

**Comment by rowleya** [comment]
It is hard to tell as it is Python code, but a quick search says no.  The reader version potentially is (by DSE).

**Comment by Christian-B** [comment]
Also AbstractDataReader.readinto and tell

**Comment by Christian-B** [comment]
Assuming not used.

**Comment by alan-stokes** [comment]
so are we deleting then? coz currently left as a raise NotImpl

**Comment by dkfellows** [comment]
`ADR.tell()` is used in `DSEFunctions.execute_break()`
